---
apiVersion: v2
name: prometheus-blackbox-exporter
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: prometheus-blackbox-exporter
  version: 7.8.0
  repository: https://prometheus-community.github.io/helm-charts

